### product index
GET http://localhost:3000/products.json


### product show
GET http://localhost:3000/products/22.json

### product create
POST http://localhost:3000/products.json 
Content-Type: application/json

{
  "name": "civic3",
  "price": "20000",
  "description": "famous car",
  "inventory": 5
}

### product update
PATCH http://localhost:3000/products/1.json 
Content-Type: application/json

{
  "name": "iphone16",
  "price": "1000",
  "description": "usb-c",
  "inventory": "50"
}

### product delete
DELETE http://localhost:3000/products/21.json

### User create signup
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name2",
  "email": "test2@test.com",
  "password": "password",
  "password_confirmation": "password"
}