### product index
GET http://localhost:3000/products.json


### product show
GET http://localhost:3000/products/2.json

### product create
POST http://localhost:3000/products.json 
Content-Type: application/json

{
  "name": "civic",
  "price": "20000",
  "image_url": "www.google.com",
  "description": "famous car"
}

### product update
PATCH http://localhost:3000/products/24.json 
Content-Type: application/json

{
  "id": "105",
  "name": "iphone16",
  "price": "1000",
  "image_url": "apple.com",
  "description": "usb-c"
}

### product delete
DELETE http://localhost:3000/products/21.json